version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./:/app
  stop_signal: SIGINT
  depends_on: 
  - mysqldb

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
  secrets:
  - db_root_password
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

secrets:
  db_root_password:
    file: db_root_password.txt

volumes:
  mysql:
  mysql_config:
